### ISSUE TITLE
There are RT issues

### ISSUE THREAD

**Issue by eserte** [nmelnick/Domain-PublicSuffix#2]
See https://rt.cpan.org/Ticket/Display.html?id=121222

**Comment by eyadof** [comment]
It looks like it's solved [here](https://github.com/nmelnick/Domain-PublicSuffix/blob/master/lib/Domain/PublicSuffix.pm#L254) but the fix was not released to [CPAN](https://metacpan.org/release/Domain-PublicSuffix/source/lib/Domain/PublicSuffix.pm#L254).

The issue appears on the newer OS because it comes with `PublicSuffix` package already installed.

**Comment by nmelnick** [comment]
This has been released under 0.15.
