### ISSUE TITLE
Root domain not matching

### ISSUE THREAD

**Issue by toddbruner** [nmelnick/Domain-PublicSuffix#3]
Downloaded latest public_suffix_list.dat.
Latest Domain::PublicSuffix (0.14)
perl v5.22.1

```
my $foo = "com.ac";
my $bar = "m.com.ac";
my $dps = Domain::PublicSuffix->new({datafile => "./public_suffix_list.dat"});
say $dps->get_root_domain($foo);
say $dps->error();
say $dps->get_root_domain($bar);
say $dps->error();
```

I would expect:
```
com.ac

m.com.ac
```

Get:
```

Domain not Valid!
m.com.ac 

```
In other words, I'd expect a valid TLD (com.ac) to not give a "Domain not Valid" Error.

**Comment by nmelnick** [comment]
Sorry for the long delay on this issue, for some reason, I had disabled notifications here.

This is a bug, but a slightly different response. Since "com.ac" cannot resolve on its own, it is not a valid root domain. However, since all of the associated data is there, there's no reason why ->suffix and ->tld wouldn't respond, since that part is completely valid.

This has been fixed in cd7e58f and released to CPAN in version 0.15.

**Comment by miyagawa** [comment]
I don't know what the change was but 0.15 seems totally broken for wildcard and exceptions.

code
```
use Domain::PublicSuffix;
use v5.20;

say "VERSION = ", Domain::PublicSuffix->VERSION;

my $d = Domain::PublicSuffix->new;

for my $domain (
    'www.kawasaki.jp',
    'city.kawasaki.jp',
    'example.city.kawasaki.jp',
) {
    say "$domain = ", $d->get_root_domain($domain);
}
```

0.14:
```
VERSION = 0.14
www.kawasaki.jp = 
city.kawasaki.jp = city.kawasaki.jp
example.city.kawasaki.jp = city.kawasaki.jp
```

0.15:
```
VERSION = 0.15
www.kawasaki.jp = 
city.kawasaki.jp = 
example.city.kawasaki.jp = 
```

**Comment by nmelnick** [comment]
Managed to miss this comment, @miyagawa, sorry about that. Version 0.16 should resolve those inconsistencies, and my tests on those domains, as well as the test suite from publicsuffix.org, pass successfully.

**Comment by nmelnick** [comment]
I am going to close this issue as the original issue seems to be solved. If there are further inconsistencies, please open a new issue.
